name: Release

on:
  workflow_dispatch:
    inputs:
      beta_release:
        required: true
        default: 'false'

jobs:
  package:
    name: Package platforms
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - uses: android-actions/setup-android@v2

      - name: Add android sdk build tools to PATH
        run: |
          cd $ANDROID_SDK_ROOT/build-tools/30.0.3
          ls -l
          echo "${{ env.ANDROID_SDK_ROOT }}/build-tools/30.0.3" >> $GITHUB_PATH
          echo "GITHUB_PATH = $GITHUB_PATH"
          echo "PATH = $PATH"

      - name: Install cordova
        run: |
          npm install -g cordova@9.0.0
          pushd res/android
          cordova telemetry off
          cordova prepare
          popd

      - name: Install dependencies
        run: npm install

      - name: Create packages
        run: |
          npm run package:chromium
          npm run package:firefox
          npm run package:android
        env:
          BETA: ${{ github.event.inputs.beta_release == 'true' }}

      - name: Set release version env var
        run: |
          echo "RELEASE_VERSION=$(cat PACKAGE_VERSION)" >> $GITHUB_ENV

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: ${{ github.event.inputs.beta_release == 'true' }}
          tag_name: v${{ env.RELEASE_VERSION }}
          body_path: CHANGELOG.md
          files: |
            dist/xbrowsersync_${{ env.RELEASE_VERSION }}_chromium.zip
            dist/xbrowsersync_${{ env.RELEASE_VERSION }}_firefox.xpi
            dist/xbrowsersync_${{ env.RELEASE_VERSION }}_android.apk
            dist/xbrowsersync_${{ env.RELEASE_VERSION }}_android_unsigned.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
